sudo: required

language: generic

matrix:
  fast_finish: true
  include:
    - os: linux
      env: CC=gcc
      services: docker
      script: ./ci/alpine.sh
    - os: linux
      env: CC=clang
      services: docker
      script: ./ci/alpine.sh
    - os: osx
      env: CC=clang
      script: ./ci/osx.sh
  allow_failures:
    - os: osx
      env: CC=clang
      script: ./ci/osx.sh
