sudo: required

language: generic

matrix:
  include:
    - os: linux
      env: CC=gcc
      services: docker
      script: ./ci/alpine.sh
    - os: linux
      env: CC=clang
      services: docker
      script: ./ci/alpine.sh
